// <auto-generated/>
namespace UI
{
    using System;
    using System.Windows.Forms;

    public partial class Login : Form
    {
        private Principal PrincipalForm;

        public Login()
        {
            InitializeComponent();
            PrincipalForm = new Principal();
        }

        private void Form1_Load(object sender, EventArgs e)
        {

        }

        private void btn_ingresar_Click(object sender, EventArgs e)
        {
            string usuario = txt_user.Text;
            string contraseña = txt_contraseña.Text;

            bool ingresa = BLL.Usuario.Getinstancia().LogIn(usuario, contraseña);

            if (ingresa)
            {
                this.Close();
                PrincipalForm.Show();
            }
            else
            {
                MessageBox.Show("Su cuenta ha sido bloqueada contacte al Administrador");
            }
        }

        private void cbo_idioma_SelectedIndexChanged(object sender, EventArgs e)
        {

        }

        private void btn_salir_Click(object sender, EventArgs e)
        {
            this.Close();
        }
    }
}
