// <auto-generated/>
namespace UI
{
    using System;
    using System.Windows.Forms;

    public partial class Principal : Form, IPrincipal
    {
        private static Principal instancia;
        private Venta_de_productos venta_De_Productos;
        private ABMusuario abmUsuario;
        private Bitacora bitacora;

        private Principal()
        {
            InitializeComponent();
            venta_De_Productos = new Venta_de_productos();
            abmUsuario = new ABMusuario();
            bitacora = new Bitacora();
        }

        public static Principal GetInstancia()
        {
            if(instancia == null)
            {
                instancia = new Principal();
            }
            return instancia;
        }

        private void Principal_Load(object sender, EventArgs e)
        {

        }

        private void nuevaVenta_Click(object sender, EventArgs e)
        {
            this.Hide();
            venta_De_Productos.Show();
        }

        private void usuariosToolStripMenuItem_Click(object sender, EventArgs e)
        {

        }

        private void usuariosToolStripMenuItem_Click_1(object sender, EventArgs e)
        {
            this.Hide();
            abmUsuario.Show();
        }

        private void bitacoraToolStripMenuItem_Click(object sender, EventArgs e)
        {
            this.Hide();
            bitacora.Show();
        }
    }
}
