// <auto-generated/>
namespace UI
{
    using Autofac;
    using Autofac.Configuration;
    using Microsoft.Extensions.Configuration;
    using System;
    using System.Windows.Forms;

    static class Program
    {
        /// <summary>
        /// Punto de entrada principal para la aplicación.
        /// </summary>
        [STAThread]
        static void Main()
        {
            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);


            var config = new ConfigurationBuilder();
            config.AddJsonFile("autofac.json");
            var containerBuilder = new ContainerBuilder();
            containerBuilder.RegisterModule(new ConfigurationModule(config.Build()));
            containerBuilder.Build();

            Application.Run(new Login());
        }
    }
}
