// <auto-generated/>
namespace UI
{
    using BLL;
    using DAL.Dao;
    using System;
    using System.Windows.Forms;

    static class Program
    {
        /// <summary>
        /// Punto de entrada principal para la aplicación.
        /// </summary>
        [STAThread]
        static void Main()
        {
            log4net.Config.XmlConfigurator.Configure();
            log4net.Core.Level nivelAlto = new log4net.Core.Level(50000, "ALTA");
            log4net.LogManager.GetRepository().LevelMap.Add(nivelAlto);
            log4net.Core.Level nivelMedio = new log4net.Core.Level(40000, "MEDIA");
            log4net.LogManager.GetRepository().LevelMap.Add(nivelAlto);
            log4net.Core.Level nivelBajo = new log4net.Core.Level(30000, "BAJA");
            log4net.LogManager.GetRepository().LevelMap.Add(nivelBajo);

            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);
            Application.Run(
                new Login(
                IoCContainer.Resolve<IIdiomaBLL>(),
                IoCContainer.Resolve<IDigitoVerificador>(),
                IoCContainer.Resolve<ITraductor>()));

            //Application.Run(new BackupUI());
            //Application.Run(new BloqueoUsuario(IoCContainer.Resolve<IUsuarioBLL>()));
            //Application.Run(new ABMusuario(IoCContainer.Resolve<IBitacoraBLL>(), IoCContainer.Resolve<IFormControl>(), IoCContainer.Resolve<IFamiliaBLL>(), IoCContainer.Resolve<IPatenteBLL>(), IoCContainer.Resolve<IDigitoVerificador>()));
        }
    }
}
