// <auto-generated/>
namespace UI
{
    using System;
    using System.Windows.Forms;

    public partial class Venta_de_productos : Form
    {
        public Venta_de_productos()
        {
            InitializeComponent();
        }

        private void label1_Click(object sender, EventArgs e)
        {
        }

        private void label2_Click(object sender, EventArgs e)
        {
        }

        private void dataGridView1_CellContentClick(object sender, DataGridViewCellEventArgs e)
        {
        }

        private void Venta_de_productos_Load(object sender, EventArgs e)
        {

        }
    }
}
