// <auto-generated/>
namespace UI
{
    using BE.Entidades;
    using BLL;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Windows.Forms;

    public partial class AdminFamUsuario : Form, IAdminFam
    {
        private const string lblUsu = "Usuario: ";
        private readonly IPatenteBLL patenteBLL;
        private readonly IFamiliaBLL familiaBLL;
        private IABMUsuario aBMUsuario;

        public Usuario UsuarioSeleccionado { get; set; } = new Usuario();

        public Familia FamiliaUsuarioSeleccionada { get; set; } = new Familia();

        public Familia FamiliaSistemaSeleccionada { get; set; } = new Familia();

        public AdminFamUsuario(IFamiliaBLL familiaBLL, IPatenteBLL patenteBLL)
        {
            InitializeComponent();
            this.familiaBLL = familiaBLL;
            this.patenteBLL = patenteBLL;
        }

        private void AdminFamUsuario_Load(object sender, EventArgs e)
        {
            aBMUsuario = IoCContainer.Resolve<IABMUsuario>();

            UsuarioSeleccionado = aBMUsuario.ObtenerUsuarioSeleccionado();

            CargarListas();

            ActualizarSeleccionado();

            CargarLbl();
        }

        private void CargarLbl()
        {
            lblUsuario.Text = string.Empty;
            lblUsuario.Text = lblUsu + UsuarioSeleccionado.Email;
        }

        private void ActualizarSeleccionado()
        {
            var descFamiliaSistema = FamSistema.GetItemText(FamSistema.SelectedItem);
            var descFamiliaUsuario = FamUsuario.GetItemText(FamUsuario.SelectedItem);

            if (!(descFamiliaSistema == string.Empty))
            {
                FamiliaSistemaSeleccionada = familiaBLL.ObtenerFamiliaConDescripcion(descFamiliaSistema);
            }

            if (!(descFamiliaUsuario == string.Empty))
            {
                FamiliaUsuarioSeleccionada = familiaBLL.ObtenerFamiliaConDescripcion(descFamiliaUsuario);
            }
        }

        private void CargarListas()
        {
            LimpiarListas();

            CargarFamiliaSistema();
            CargarFamiliaUsuario();
        }

        private void LimpiarListas()
        {
            FamUsuario.ClearSelected();
            FamSistema.ClearSelected();
            FamUsuario.SelectedItem = null;
            FamSistema.DataSource = null;
            FamUsuario.DataSource = null;
        }

        private void CargarFamiliaUsuario()
        {
            var familiasUsuario = UsuarioSeleccionado.Familia.Select(fam => fam.Descripcion).ToList();

            if (familiasUsuario.Count > 0)
            {
                FamUsuario.DataSource = UsuarioSeleccionado.Familia.Select(fam => fam.Descripcion).ToList();
            }
            else
            {
                FamUsuario.DataSource = null;
            }
        }

        private void CargarFamiliaSistema()
        {
            var familiasBd = familiaBLL.Cargar().Select(fam => fam.Descripcion).ToList();

            if (familiasBd.Count > 0)
            {
                FamSistema.DataSource = familiaBLL.Cargar().Select(fam => fam.Descripcion).ToList();
            }
            else
            {
                FamSistema.DataSource = null;
            }
        }

        private void btnVolver_Click(object sender, EventArgs e)
        {
            LimpiarListas();

            this.Hide();
        }

        private void btnQuitar_Click(object sender, EventArgs e)
        {
            ActualizarSeleccionado();

            var permitir = patenteBLL.CheckeoFamiliaParaBorrar(FamiliaUsuarioSeleccionada, aBMUsuario.ObtenerUsuariosBd());

            if (permitir)
            {

                if (UsuarioSeleccionado.Familia.Any(famUsu => famUsu.FamiliaId == FamiliaUsuarioSeleccionada.FamiliaId))
                {
                    UsuarioSeleccionado.Familia.RemoveAll(famUsu => famUsu.FamiliaId == FamiliaUsuarioSeleccionada.FamiliaId);
                }

                familiaBLL.BorrarFamiliasUsuario(new List<Familia>() { FamiliaUsuarioSeleccionada }, UsuarioSeleccionado.UsuarioId);

            }
            else
            {
                Alert.ShowSimpleAlert("No puede quitar esta familia", "MSJ035");
            }

            CargarListas();
        }

        private void btnAsignar_Click(object sender, EventArgs e)
        {
            ActualizarSeleccionado();

            if (!UsuarioSeleccionado.Familia.Any(famUsu => famUsu.FamiliaId == FamiliaUsuarioSeleccionada.FamiliaId))
            {
                UsuarioSeleccionado.Familia.Add(FamiliaSistemaSeleccionada);
            }

            familiaBLL.GuardarFamiliasUsuario(new List<int>() { FamiliaSistemaSeleccionada.FamiliaId }, UsuarioSeleccionado.UsuarioId);

            CargarListas();
        }
    }
}
