// <auto-generated/>
namespace UI
{
    using BE.Entidades;
    using BLL.Imp;
    using System;
    using System.Collections.Generic;
    using System.Windows.Forms;

    public partial class AdminPatFamilia : Form, IAdminPatFamilia
    {
        public IPatenteBLL patenteBLL;

        public AdminPatFamilia(IPatenteBLL patenteBLL)
        {
            InitializeComponent();
            this.patenteBLL = patenteBLL;
        }

        public void AsignarPatentes(int familiaId, List<int> patentesId)
        {
            if (patentesId != null)
            {
                var asignadas = patenteBLL.AsignarPatentes(familiaId, patentesId);
                if (asignadas)
                {

                }
            }
        }

        public void NegarPatentes(int familiaId, List<int> patentesId)
        {
            if (patentesId != null)
            {
                var negadas = patenteBLL.NegarPatentes(familiaId, patentesId);
                if (negadas)
                {

                }
            }

        }

        public Patente ObtenerPatentesSeleccion()
        {
            throw new NotImplementedException();
        }

        private void AdminPatFamilia_Load(object sender, EventArgs e)
        {
            lstPatentes.DataSource = patenteBLL.Cargar();
        }

        private void lstPatentes_SelectedIndexChanged(object sender, EventArgs e)
        {

        }
    }
}
