// <auto-generated/>
namespace UI
{
    using DAL.Utils;
    using Microsoft.SqlServer.Management.Common;
    using Microsoft.SqlServer.Management.Smo;
    using System;
    using System.Windows.Forms;

    public partial class BackupUI : Form
    {
        public BackupUI()
        {
            InitializeComponent();
        }

        private void Backup_Load(object sender, EventArgs e)
        {

        }

        private void btnAceptar_Click(object sender, EventArgs e)
        {
            progressBar1.Value = 0;

            try
            {
                var dbServer = new Server(new ServerConnection(SqlUtils.Connection()));
                var dbBackUp = new Backup() { Action = BackupActionType.Database, Database = "SYSANALIZER2" };
                dbBackUp.Devices.AddDevice(@"C:\Data\SYSANALIZER2.bak", DeviceType.File);
                dbBackUp.Initialize = true;
                dbBackUp.PercentComplete += DbPercentComplete;
                dbBackUp.Complete += DbBackUp_Complete;
                dbBackUp.SqlBackupAsync(dbServer);
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message, "Hubo un error", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }

        private void DbBackUp_Complete(object sender, Microsoft.SqlServer.Management.Common.ServerMessageEventArgs e)
        {
            if (e.Error != null)
            {
                lblStatus.Invoke((MethodInvoker)delegate
                {
                    lblStatus.Text = e.Error.Message;
                });
            }
        }

        private void DbPercentComplete(object sender, PercentCompleteEventArgs e)
        {
            progressBar1.Invoke((MethodInvoker)delegate
            {
                progressBar1.Value = e.Percent;
                progressBar1.Update();
            });

            lblProgreso.Invoke((MethodInvoker)delegate
            {
                lblProgreso.Text = $"{e.Percent}%";
            });
        }
    }
}
