// <auto-generated/>
namespace UI
{
    using BLL;
    using System;
    using System.Windows.Forms;

    public partial class Bitacora : Form, IBitacora
    {
        private readonly IUsuarioBLL usuarionBll;

        public Bitacora()
        {
            InitializeComponent();
            usuarionBll = IoCContainer.Resolve<IUsuarioBLL>();
        }

        private void Bitacora_Load(object sender, EventArgs e)
        {
            FillCheckedList();
        }

        private void btn_volver_Click(object sender, EventArgs e)
        {
            Hide();
        }

        private void FillCheckedList()
        {
           var userList = usuarionBll.Cargar();
            
            foreach (var usu in userList)
            {
                checkListUsuarios.Items.Add(usu.Nombre);
            }
        }

        private void btn_filtrar_Click(object sender, EventArgs e)
        {

        }
    }
}
