// <auto-generated/>
namespace UI
{
    using System;
    using System.Windows.Forms;

    public partial class BloqueUsuario : Form, IBloqueoUsuario
    {
        public BloqueUsuario()
        {
            InitializeComponent();
        }

        private void BloqueUsuario_Load(object sender, EventArgs e)
        {
            
        }

        private void btnVolver_Click(object sender, EventArgs e)
        {
            Hide();
        }

        private void BloqueUsuario_FormClosing(object sender, FormClosingEventArgs e)
        {
            Hide();
            DialogResult = DialogResult.OK;
            e.Cancel = true;
        }
    }
}
