// <auto-generated/>
namespace UI
{
    using BLL;
    using System;
    using System.Linq;
    using System.Windows.Forms;

    public partial class DetalleRefForm : Form, IDetalleRefForm
    {
        private readonly IDetalleVentaBLL detalleVentaBLL;

        public DetalleRefForm(IDetalleVentaBLL detalleVentaBLL)
        {
            this.detalleVentaBLL = detalleVentaBLL;
            InitializeComponent();
        }

        private void DetalleRefForm_Load(object sender, EventArgs e)
        {
            dgDetalleVenta.AutoGenerateColumns = false;
            var ventaUI = IoCContainer.Resolve<IVentaUI>();
            CargarDetalle(ventaUI.ObtenerVentaSeleccionada().VentaId);
        }

        private void CargarDetalle(int ventaId)
        {
            dgDetalleVenta.DataSource = detalleVentaBLL.Cargar().Where(x => x.VentaId == ventaId).Select(x => x.LineasDetalle).FirstOrDefault();
        }

        private void btnVolver_Click(object sender, EventArgs e)
        {
            this.Hide();
        }
    }
}
