// <auto-generated/>
namespace UI
{
    using System;
    using System.Windows.Forms;

    public partial class DetalleRefForm : Form
    {
        public DetalleRefForm()
        {
            InitializeComponent();
        }


        private void DetalleRefForm_Load(object sender, EventArgs e)
        {

        }

        private void btnVolver_Click(object sender, EventArgs e)
        {
            this.Hide();
        }
    }
}
