// <auto-generated/>
namespace UI
{
    using BLL;
    using System;
    using System.Linq;
    using System.Windows.Forms;

    public partial class DetalleRefForm : Form, IDetalleRefForm
    {
        private readonly IDetalleVentaBLL detalleVentaBLL;
        private int VentaId { get; set; }

        public DetalleRefForm(IDetalleVentaBLL detalleVentaBLL)
        {
            this.detalleVentaBLL = detalleVentaBLL;
            InitializeComponent();
        }

        private void DetalleRefForm_Load(object sender, EventArgs e)
        {
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            dgDetalleVenta.AutoGenerateColumns = false;
            CargarDetalle();
        }

        private void CargarDetalle()
        {
            var ventaUI = IoCContainer.Resolve<IVentaUI>();
            VentaId = ventaUI.ObtenerVentaSeleccionada().VentaId;

            dgDetalleVenta.DataSource = detalleVentaBLL.Cargar()
                                                       .Where(x => x.VentaId == VentaId)
                                                       .SelectMany(x => x.LineasDetalle).ToList();
        }

        private void btnVolver_Click(object sender, EventArgs e)
        {
            this.Hide();
        }
    }
}
