// <auto-generated/>
namespace UI
{
using System;
using System.Windows.Forms;
    public partial class Familias : Form
    {
        public Familias()
        {
            InitializeComponent();
        }

        private void Familias_Load(object sender, EventArgs e)
        {

        }
    }
}
