// <auto-generated/>
namespace UI
{
    using BE.Entidades;
    using BLL;
    using Microsoft.VisualBasic;
    using System;
    using System.Collections.Generic;
    using System.Windows.Forms;

    public partial class Familias : Form, IFamilias
    {
        private readonly IFamiliaBLL familiaBLL;
        private readonly IAdminPatFamilia adminPatFamilia;

        public Familias(IFamiliaBLL familiaBLL, IUsuarioBLL usuarioBLL, IAdminPatFamilia adminPatFamilia)
        {
            InitializeComponent();
            this.familiaBLL = familiaBLL;
            this.adminPatFamilia = adminPatFamilia;
        }

        private void Familias_Load(object sender, EventArgs e)
        {
            CargarFamilias();

        }

        private void CargarFamilias()
        {
            var descripciones = new List<string>();

            foreach (var familia in familiaBLL.Cargar())
            {
                descripciones.Add(familia.Descripcion);
            }

            chklstFamilias.DataSource = descripciones;
        }

        private void btnNueva_Click(object sender, EventArgs e)
        {
            var nombreFamilia = Interaction.InputBox("Ingrese el nombre para la nueva familia", "Nueva familia", "");

            var creada = familiaBLL.Crear(new Familia() { Descripcion = nombreFamilia });
            if (creada)
            {
                var resultado = adminPatFamilia.ShowDialog();
                if (resultado == DialogResult.OK)
                {
                    var patentes = adminPatFamilia.ObtenerPatentesSeleccion();
                }
            }

            CargarFamilias();
            chklstFamilias.Refresh();
        }

        private void btnBaja_Click(object sender, EventArgs e)
        {
            var desc = chklstFamilias.SelectedItem.ToString();

            familiaBLL.Borrar(new Familia() { Descripcion = desc, FamiliaId = familiaBLL.ObtenerIdFamiliaPorDescripcion(desc) });
            CargarFamilias();
            chklstFamilias.Refresh();
        }

        private void btnModificar_Click(object sender, EventArgs e)
        {
            var desc = chklstFamilias.SelectedItem.ToString();

            familiaBLL.Actualizar(new Familia() { Descripcion = desc, FamiliaId = familiaBLL.ObtenerIdFamiliaPorDescripcion(desc) });
            CargarFamilias();
            chklstFamilias.Refresh();
        }
    }
}
