// <auto-generated/>
namespace UI
{
    using BLL;
    using System;
    using System.Windows.Forms;

    public partial class Login : Form
    {
        private log4net.ILog log;
        private IPrincipal PrincipalForm;
        private IUsuarioBLL usuarionBLL;

        public Login()
        {
            InitializeComponent();
        }


        private void Form1_Load(object sender, EventArgs e)
        {
            log = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
            PrincipalForm = IoCContainer.Resolve<IPrincipal>();
            usuarionBLL = IoCContainer.Resolve<IUsuarioBLL>();
        }

        private void btn_ingresar_Click(object sender, EventArgs e)
        {
            this.CatchException(() =>
            {
                string usuario = txt_user.Text;
                string contraseña = txt_contraseña.Text;
                ////admin123
                bool ingresa = usuarionBLL.LogIn(usuario, contraseña);

                if (ingresa)
                {
                    this.Hide();
                    PrincipalForm.ComprobarSiEsPrimerLogin(usuario);
                    PrincipalForm.Show();
                }
                else
                {
                    MessageBox.Show("Su cuenta ha sido bloqueada contacte al Administrador");
                }
            },
            (ex) => MessageBox.Show($"Exploto por lo siguiente {ex.Message}"));
        }

        private void cbo_idioma_SelectedIndexChanged(object sender, EventArgs e)
        {

        }

        private void btn_salir_Click(object sender, EventArgs e)
        {
            this.Close();
        }
    }
}
