// <auto-generated/>
namespace UI
{
    using BE;
    using BLL;
    using System;
    using System.Windows.Forms;

    public partial class Login : Form
    {

        private log4net.ILog log;
        private IPrincipal PrincipalForm;
        private IUsuarioBLL usuarioBLL;
        private IFormControl formControl;

        public Login()
        {
            InitializeComponent();
        }


        private void Form1_Load(object sender, EventArgs e)
        {
            log = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
            PrincipalForm = IoCContainer.Resolve<IPrincipal>();
            usuarioBLL = IoCContainer.Resolve<IUsuarioBLL>();
            formControl = IoCContainer.Resolve<IFormControl>();
        }

        private void btn_ingresar_Click(object sender, EventArgs e)
        {
            this.CatchException(() =>
            {
                var usuario = txt_user.Text;
                var contraseña = txt_contraseña.Text;
                ////admin123
                var ingresa = usuarioBLL.LogIn(usuario, contraseña);

                if (ingresa)
                {
                    this.Hide();
                    formControl.GuardarDatosSesionUsuario(usuarioBLL.ObtenerUsuarioConEmail(usuario));
                    PrincipalForm.ComprobarSiEsPrimerLogin(usuario);
                    PrincipalForm.Show();
                }
                else
                {
                    MessageBox.Show("Login Incorrecto");
                }
            },
            (ex) => MessageBox.Show($"Exploto por lo siguiente {ex.Message}"));
        }

        private void cbo_idioma_SelectedIndexChanged(object sender, EventArgs e)
        {

        }

        private void btn_salir_Click(object sender, EventArgs e)
        {
            this.Close();
        }
    }
}
