// <auto-generated/>
namespace UI
{
    using BE.Entidades;
    using BLL;
    using System;
    using System.Linq;
    using System.Windows.Forms;

    public partial class NegarPatUsuario : Form, INegarPat
    {
        private const string lblUsu = "Usuario: ";
        private readonly IPatenteBLL patenteBLL;
        private IABMUsuario aBMUsuario;

        public Usuario UsuarioSeleccionado { get; set; } = new Usuario();

        public Patente PatenteUsuarioSeleccionada { get; set; } = new Patente();
        public Patente PatenteSistemaSeleccionada { get; set; } = new Patente();

        public NegarPatUsuario(IPatenteBLL patenteBLL)
        {
            InitializeComponent();
            this.patenteBLL = patenteBLL;
        }

        private void NegarPatUsuario_Load(object sender, EventArgs e)
        {
            aBMUsuario = IoCContainer.Resolve<IABMUsuario>();

            UsuarioSeleccionado = aBMUsuario.ObtenerUsuarioSeleccionado();

            CargarPatentes();
        }

        private void CargarPatentes()
        {
            var patentesBd = patenteBLL.Cargar();

            var patHabilitadas = patentesBd.Where(patBd => );

            if (patentesBd.Count > 0)
            {
                
            }

        }
    }
}
