// <auto-generated/>
namespace UI
{
    using BE.Entidades;
    using BLL;
    using System;
    using System.Windows.Forms;

    public partial class Productos : Form, IProductos
    {
        private readonly IProductoBLL productoBLL;

        private Producto productoSeleccionado;

        public Productos(IProductoBLL productoBLL)
        {
            this.productoBLL = productoBLL;
            InitializeComponent();
        }

        private void groupBox1_Enter(object sender, EventArgs e)
        {

        }

        private void Productos_Load(object sender, EventArgs e)
        {
            productoSeleccionado = null;
            productoBLL.Cargar();
        }

        private void btnNuevo_Click(object sender, EventArgs e)
        {
            productoBLL.Crear(new Producto() { Descripcion = txtDescripcion.Text, PVenta = float.Parse(txtPcosto.Text), PUnitario = float.Parse(txtPunitario.Text), Stock = int.Parse(txtCantidad.Text), MinStock = int.Parse(txtMinStock.Text) });
        }

        private void btnModificar_Click(object sender, EventArgs e)
        {
            productoBLL.Actualizar(new Producto() { Descripcion = txtDescripcion.Text, PVenta = float.Parse(txtPcosto.Text), PUnitario = float.Parse(txtPunitario.Text), Stock = int.Parse(txtCantidad.Text), MinStock = int.Parse(txtMinStock.Text) });
        }

        private void btnBorrar_Click(object sender, EventArgs e)
        {
            productoBLL.Borrar(new Producto() { ProductoId = int.Parse(txtNroProd.Text) });
        }

        private void btnVolver_Click(object sender, EventArgs e)
        {
            Hide();
        }

        private void btnSelVta_Click(object sender, EventArgs e)
        {
            var producto = (Producto)dgProd.CurrentRow.DataBoundItem;

            productoSeleccionado = new Producto()
            {
                Descripcion = producto.Descripcion,
                ProductoId = producto.ProductoId,
                PVenta = producto.PVenta,
                PUnitario = producto.PUnitario,
                Stock = producto.Stock,
               MinStock = producto.MinStock
            };

            DialogResult = DialogResult.OK;
        }

        public Producto GetProductoSeleccionado()
        {
            return productoSeleccionado;
        }

        private void Productos_FormClosing(object sender, FormClosingEventArgs e)
        {
            Hide();
            e.Cancel = true;
        }
    }
}
