// <auto-generated/>
namespace UI
{
using System;
using System.Windows.Forms;
    public partial class Restore : Form
    {
        public Restore()
        {
            InitializeComponent();
        }

        private void Restore_Load(object sender, EventArgs e)
        {

        }

        private void btnExaminar_Click(object sender, EventArgs e)
        {

        }
    }
}
