// <auto-generated/>
namespace UI
{
    using BE.Entidades;
    using BLL;
    using System;
    using System.Collections.Generic;
    using System.Windows.Forms;

    public partial class VentaUI : Form
    {
        private readonly IVentaBLL ventaBLL;
        private readonly ITraductor traductor;

        private const string nombreForm = "Venta";

        public LineaVenta lineaSeleccionada { get; set; } = new LineaVenta();
        public Venta ventaSeleccionada { get; set; } = new Venta();
        public List<Venta> ventasBd { get; set; } = new List<Venta>();
        public List<LineaVenta> listGrid { get; set; } = new List<LineaVenta>();

        public VentaUI(ITraductor traductor, IVentaBLL ventaBLL)
        {
            this.traductor = traductor;
            this.ventaBLL = ventaBLL;
            InitializeComponent();
        }

        private void VentaUI_Load(object sender, EventArgs e)
        {
            traductor.Traduccir(this, nombreForm);
            CargarVentas();
            CargarGrid();
        }

        private void CargarVentas()
        {
            ventasBd = ventaBLL.Cargar();

            foreach (var venta in ventasBd)
            {

            }
        }

        private void CargarGrid()
        {
            dgVenta.DataSource = null;
            dgVenta.DataSource = listGrid;
        }
    }
}
