// <auto-generated/>
namespace UI
{
    using System;
    using System.Windows.Forms;

    public partial class VtaProd : Form, IVtaProd
    {
        public VtaProd()
        {
            InitializeComponent();
        }

        private void label1_Click(object sender, EventArgs e)
        {
        }

        private void label2_Click(object sender, EventArgs e)
        {
        }

        private void dataGridView1_CellContentClick(object sender, DataGridViewCellEventArgs e)
        {
        }

        private void VtaProd_Load(object sender, EventArgs e)
        {

        }

        private void btnFinalizar_Click(object sender, EventArgs e)
        {

        }

        private void btnVolver_Click(object sender, EventArgs e)
        {
            this.Hide();
            //var principal = Principal.GetInstancia();
            //principal.Show();
        }
    }
}
